version = 0.1
[default.deploy.parameters]
stack_name = "authentication-marketwiz"
resolve_s3 = true
s3_prefix = "authentication-marketwiz"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
